server:
  port: 8082

spring:
  application:
    name: module-core-mapper

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.point.dto
  configuration:
    map-underscore-to-camel-case: true
  